# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%=ENV['C9_USER']%>
  password: 
  host: localhost

development:
  <<: *default
  database: c9

test:
  <<: *default
  database: c9

production:
  <<: *default
  database: c9
  username: <%=ENV['C9_USER']%>
  password: 

